version: '3.7'
services:
  backend:
    build: 
      context: ./backend
    container_name: mindfinder_backend
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./backend:/python-docker/
  frontend:
    build: 
      context: ./frontend
    container_name: mindfinder_frontend
    restart: always
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html/
    depends_on:
      - backend